spring:
  application:
    name: COMMENTS-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

  sleuth:
    sampler:
      probability: 1.0 # 1.0 means 100% logging 0.1 means 10% of logging will be traced

  zipkin:
    base-url: ${ZIPKIN_BASE_URL}

  rabbitmq:
    password: ${RABBITMQ_PASSWORD:guest}
    username: ${RABBITMQ_USERNAME:guest}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
  #config:
  # import: optional:configserver:http://localhost:8888/

service:
  welcome:
    msg: Welcome To Comment Service

server:
  port: 8281

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

  instance: localhost

comment-rmq:
  queue-name: comment-pub
  direct-exchange: comment-direct-exchange
  topic-exchange: comment-topic-exchange
  topic-routing-key: "comment.topic.#" # Note => topic is dot(.) separated name.  Use by Exchange to filter Messages to queue

comment-serv-topic:
  daily: "comment.topic.daily"
  exchange: "comment-topic-exchange"