version: "3"
# To avoid LogBack config creation Error of DB not supporting generated-Key etc
# Create Database for each services after and restart all microservices e.g.
#  CREATE DATABASE `productdb` /*!40100 DEFAULT CHARACTER SET latin1 */;
#  CREATE DATABASE `appuserdb` /*!40100 DEFAULT CHARACTER SET latin1 */;
#  CREATE DATABASE `commentdb` /*!40100 DEFAULT CHARACTER SET latin1 */;
#  CREATE DATABASE `ratingdb` /*!40100 DEFAULT CHARACTER SET latin1 */;
#  CREATE DATABASE `dashboarddb` /*!40100 DEFAULT CHARACTER SET latin1 */;

services:
  # Service Discovery - Eureka server with memory limit of 700m for demo purposes only
  eureka-server:
    container_name: eureka-server
    image: torrydocker/eureka-server:latest
    ports:
      - "8761:8761"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - review-compose-network
  # Sleuth/Zipkin Server - Distributed Tracing
  zipkin-server:
    container_name: zipkin-server
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
#    environment:
#      SPRING_ZIPKIN_URL: "http://localhost:9411/zipkin"
    networks:
      - review-compose-network
# RabbitMQ for Zipkin
  rabbit-mq-zipkin:
    container_name: rabbitmq-server
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: localhost
      RABBITMQ_PORT: 5672
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - review-compose-network
  # API-Gateway
  api-gateway:
    depends_on:
      - zipkin-server
      - eureka-server
      - rabbit-mq-zipkin
    container_name: api-gateway
    image: torrydocker/api-gateway:latest
    ports:
      - "9001:9001"
    environment:
      EUREKA_DEFAULT_ZONE: "http://eureka-server:8761/eureka/"
      ZIPKIN_BASE_URL: "http://zipkin-server:9411/"
    networks:
      - review-compose-network
  # Database Service - H2 used for dev and test
  db:
    container_name: mysql-container
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: <DB-PASSWORD>
    restart: always
    networks:
      - review-compose-network
  # Review Service
  reviews-service:
    container_name: reviews-service
    image: torrydocker/review-service:latest
    depends_on:
      - zipkin-server
      - eureka-server
      - rabbit-mq-zipkin
      - api-gateway
    environment:
      EUREKA_DEFAULT_ZONE: "http://eureka-server:8761/eureka/"
      ZIPKIN_BASE_URL: "http://zipkin-server:9411/"
      API_GATEWAY_BASE_URL: "http://api-gateway:9001/"
      RABBITMQ_PASSWORD: guest
      RABBITMQ_USERNAME: guest
      RABBITMQ_HOST:  rabbitmq-server
      RABBITMQ_PORT: 5672
    ports:
      - "8481:8481"
    networks:
      - review-compose-network
  # Rating-Service
  rating-service:
    depends_on:
      - zipkin-server
      - eureka-server
      - rabbit-mq-zipkin
      - db
      - api-gateway
    container_name: rating-service
    image: torrydocker/ratingservice:rmq-1.0.0
    environment:
      PROFILE: dev
      DB_HOST: mysql-container
      DB_PORT: 3306
      DB_NAME: ratingdb
      DB_USER: <DB-USER>
      DB_PASSWORD: <DB-PASSWORD>
      EUREKA_DEFAULT_ZONE: "http://eureka-server:8761/eureka/"
      ZIPKIN_BASE_URL: "http://zipkin-server:9411/"
      API_GATEWAY_BASE_URL: "http://api-gateway:9001/"
      SMTP: smtp.gmail.com
      SMTP_PORT: 587
      LOG_BACK_USER_NAME: <USER_EMAIL>
      LOG_BACK_PASSWORD: <USER_EMAIL_PASSWORD>
      LOG_RECIPIENT_EMAIL: <RECIPIENT_EMAIL>
      LOG_SENDER_EMAIL: <SENDER_EMAIL>
      RABBITMQ_PASSWORD: guest
      RABBITMQ_USERNAME: guest
      RABBITMQ_HOST: rabbitmq-server
      RABBITMQ_PORT: 5672
    networks:
      - review-compose-network
    ports:
      - "8181:8181"
  # Product Service
  product-service:
    depends_on:
      - eureka-server
      - zipkin-server
      - rabbit-mq-zipkin
      - api-gateway
      - db
    container_name: product-service
    image: torrydocker/productservice:rmq-1.0.0
    environment:
      PROFILE: test
      DB_HOST: mysql-container
      DB_PORT: 3306
      DB_NAME: productdb
      DB_USER: <DB-USER>
      DB_PASSWORD: <DB-PASSWORD>
      EUREKA_DEFAULT_ZONE: "http://eureka-server:8761/eureka/"
      ZIPKIN_BASE_URL: "http://zipkin-server:9411/"
      API_GATEWAY_BASE_URL: "http://api-gateway:9001/"
      SMTP: <SMTP-HOST-NAME e.g. smtp.gmail.com for GMail>
      SMTP_PORT: 587
      LOG_BACK_USER_NAME: <USER_EMAIL>
      LOG_BACK_PASSWORD: <USER_EMAIL_PASSWORD>
      LOG_RECIPIENT_EMAIL: <RECIPIENT_EMAIL>
      LOG_SENDER_EMAIL: <SENDER_EMAIL>
      RABBITMQ_PASSWORD: guest
      RABBITMQ_USERNAME: guest
      RABBITMQ_HOST: rabbitmq-server
      RABBITMQ_PORT: 5672
    ports:
      - "8381:8381"
    networks:
      - review-compose-network

# App-User Service
  app-user-service:
    depends_on:
      - db
      - api-gateway
      - rabbit-mq-zipkin
      - eureka-server
      - zipkin-server
    container_name: app-user-service
    image: torrydocker/appuser:rmq-1.0.0
    environment:
      PROFILE: test
      DB_HOST: mysql-container
      DB_PORT: 3306
      DB_NAME: appuserdb
      DB_USER: <DB-USER-NAME>
      DB_PASSWORD: <DB-PASSWORD>
      EUREKA_DEFAULT_ZONE: "http://eureka-server:8761/eureka/"
      ZIPKIN_BASE_URL: "http://zipkin-server:9411/"
      API_GATEWAY_BASE_URL: "http://api-gateway:9001/"
      SMTP: <SMTP-HOST-NAME e.g. smtp.gmail.com for GMail>
      SMTP_PORT: 587
      LOG_BACK_USER_NAME: <USER_EMAIL>
      LOG_BACK_PASSWORD: <USER_EMAIL_PASSWORD>
      LOG_RECIPIENT_EMAIL: <RECIPIENT_EMAIL>
      LOG_SENDER_EMAIL: <SENDER_EMAIL>
      RABBITMQ_PASSWORD: guest
      RABBITMQ_USERNAME: guest
      RABBITMQ_HOST: rabbitmq-server
      RABBITMQ_PORT: 5672
    ports:
      - "8081:8081"
    networks:
      - review-compose-network
# Comment-Service
  comment-service:
    depends_on:
      - db
      - api-gateway
      - eureka-server
      - zipkin-server
      - rabbit-mq-zipkin
    container_name: comment-service
    image: torrydocker/commentservice:rmq-1.0.0
    environment:
      PROFILE: dev
      DB_HOST: mysql-container
      DB_PORT: 3306
      DB_NAME: commentdb
      DB_USER: <DB-USER-NAME>
      DB_PASSWORD: <DB-PASSWORD>
      EUREKA_DEFAULT_ZONE: "http://eureka-server:8761/eureka/"
      ZIPKIN_BASE_URL: "http://zipkin-server:9411/"
      API_GATEWAY_BASE_URL: "http://api-gateway:9001/"
      SMTP: <SMTP-HOST-NAME e.g. smtp.gmail.com for GMail>
      SMTP_PORT: 587
      LOG_BACK_USER_NAME: <USER_EMAIL>
      LOG_BACK_PASSWORD: <USER_EMAIL_PASSWORD>
      LOG_RECIPIENT_EMAIL: <RECIPIENT_EMAIL>
      LOG_SENDER_EMAIL: <SENDER_EMAIL>
      RABBITMQ_PASSWORD: guest
      RABBITMQ_USERNAME: guest
      RABBITMQ_HOST: rabbitmq-server
      RABBITMQ_PORT: 5672
    ports:
      - "8281:8281"
    networks:
      - review-compose-network
  # Dashboard Service
  dashboard:
    restart: on-failure
    depends_on:
      - eureka-server
      - zipkin-server
      - rmq
    container_name: dashboard-container
    image: torrydocker/dashboard:rmq-1.0.0
    networks:
      - app-user-network
    environment:
      PROFILE: dev
      DB_DRIVER: com.mysql.cj.jdbc.Driver
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: dashboarddb # For Logging
      DB_USER: <DB-USER-NAME>
      DB_PASSWORD: <DB-PASSWORD>
      EUREKA_DEFAULT_ZONE: "http://eureka-server:8761/eureka/"
      ZIPKIN_BASE_URL: "http://zipkin-server:9411/"
      SMTP: <SMTP-HOST-NAME e.g. smtp.gmail.com for GMail>
      SMTP_PORT: 587
      LOG_BACK_USER_NAME: <USER_EMAIL>
      LOG_BACK_PASSWORD: <USER_EMAIL_PASSWORD>
      LOG_RECIPIENT_EMAIL: <RECIPIENT_EMAIL>
      LOG_SENDER_EMAIL: <SENDER_EMAIL>
      RABBITMQ_PASSWORD: guest
      RABBITMQ_USERNAME: guest
      RABBITMQ_HOST: rabbitmq-server
      RABBITMQ_PORT: 5672
    ports:
      - "9100:9100"
# Network
networks:
  review-compose-network: