service:
  welcome:
    msg: Welcome To App User Service

server:
  port: 8081

spring:
  profiles:
    active: ${PROFILE:test}

  application:
    name: app-user-service

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME} # To-Do Database to be created
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create-drop
  h2:
    console:
      enabled: true  # Enable Access to H2 client Console http://localhost:8081/h2-console/login.jsp
    # config:
    #  import: optional:configserver:http://localhost:8888/

  sleuth:
    sampler:
      probability: 1.0 # 1.0 means 100% logging 0.1 means 10% of logging will be traced

  zipkin:
    base-url: ${ZIPKIN_BASE_URL}

  rabbitmq:
    password: ${RABBITMQ_PASSWORD:guest}
    username: ${RABBITMQ_USERNAME:guest}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

  instance: localhost

app-user-rmq:
  queue-name: app-user-pub
  direct-exchange: app-user-exchange
  direct-routing-key: app-rout-pub-key
  topic-exchange: app-user-topic-exchange
  topic-routing-key: "app.user.#" # Use by Exchange to filter Messages to queue i.e. Every Message with routing key starting with app.user will stream to app-user queue

app-user-topic:
  daily: "app.user.topic.daily"