spring:
  application:
    name: app-user-service

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME} # To-Do Database to be created
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  rabbitmq:
    password: ${RABBITMQ_PASSWORD:guest}
    username: ${RABBITMQ_USERNAME:guest}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}

  sleuth:
    sampler:
      probability: 1.0 # 1.0 means 100% logging 0.1 means 10% of logging will be traced

  zipkin:
    base-url: ${ZIPKIN_BASE_URL}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

  #config:
   # import: optional:configserver:http://localhost:8888/

server:
  port: 8081

app-user-rmq:
  queue-name: app-user-pub
  direct-exchange: app-user-exchange
  direct-routing-key: app-rout-pub-key
  topic-exchange: app-user-topic-exchange
  topic-routing-key: "app.user.#" # Use by Exchange to filter Messages to queue i.e. Every Message with routing key starting with app.user will stream to app-user queue

app-user-topic:
  daily: "app.user.topic.daily"
