spring:

  application:
    name: COMMENTS-SERVICE

  profiles:
    active: ${PROFILE:test}
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: user
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: 'create-drop'
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true;

  sleuth:
    sampler:
      probability: 1.0 # 1.0 means 100% logging 0.1 means 10% of logging will be traced

  zipkin:
    base-url: ${ZIPKIN_BASE_URL}

  rabbitmq:
    password: ${RABBITMQ_PASSWORD:guest}
    username: ${RABBITMQ_USERNAME:guest}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

  instance: localhost

#  instance: localhost
 # config:
  #  import: optional:configserver:http://localhost:8888/

service:
  welcome:
    msg: Welcome To Comment Service

server:
  port: 8281

comment-rmq:
  queue-name: comment-pub
  direct-exchange: comment-direct-exchange
  topic-exchange: comment-topic-exchange
  topic-routing-key: "comment.topic.#" # Note => topic is dot(.) separated name.  Use by Exchange to filter Messages to queue

comment-serv-topic:
  daily: "comment.topic.daily"
  exchange: "comment-topic-exchange"